<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Recipe;
use App\Models\Tag;
use App\Models\User;
use Illuminate\Database\Seeder;

class RecipeSeeder extends Seeder
{
    public function run(): void
    {
        $chefRina  = User::where('email', 'chef.rina@rasarekomendasi.id')->first();
        $chefBudi  = User::where('email', 'chef.budi@rasarekomendasi.id')->first();
        $chefDewi  = User::where('email', 'chef.dewi@rasarekomendasi.id')->first();

        $catIndo    = Category::where('slug', 'masakan-indonesia')->first();
        $catAsia    = Category::where('slug', 'masakan-asia')->first();
        $catDessert = Category::where('slug', 'dessert-kue')->first();
        $catSehat   = Category::where('slug', 'makanan-sehat')->first();
        $catSeafood = Category::where('slug', 'seafood')->first();

        $recipes = [
            // ── CHEF RINA SARI (Indonesian & Jawa) ─────────────────────────────────
            [
                'chef_id'       => $chefRina->id,
                'category_id'   => $catIndo->id,
                'title'         => 'Rendang Daging Sapi Panggang',
                'description'   => 'Rendang adalah masakan khas Minangkabau yang kaya rempah. Daging sapi dimasak perlahan dengan santan dan bumbu rempah hingga mengering dan berwarna cokelat kehitaman.',
                'ingredients'   => [
                    ['name' => 'Daging sapi', 'amount' => '1', 'unit' => 'kg'],
                    ['name' => 'Santan kelapa', 'amount' => '800', 'unit' => 'ml'],
                    ['name' => 'Bawang merah', 'amount' => '15', 'unit' => 'siung'],
                    ['name' => 'Bawang putih', 'amount' => '8', 'unit' => 'siung'],
                    ['name' => 'Cabai merah keriting', 'amount' => '20', 'unit' => 'buah'],
                    ['name' => 'Lengkuas', 'amount' => '3', 'unit' => 'cm'],
                    ['name' => 'Serai', 'amount' => '3', 'unit' => 'batang'],
                    ['name' => 'Daun salam', 'amount' => '5', 'unit' => 'lembar'],
                    ['name' => 'Kunyit', 'amount' => '2', 'unit' => 'cm'],
                    ['name' => 'Garam', 'amount' => '2', 'unit' => 'sdt'],
                ],
                'cooking_steps' => [
                    ['step' => 1, 'instruction' => 'Haluskan bawang merah, bawang putih, cabai, lengkuas, dan kunyit.'],
                    ['step' => 2, 'instruction' => 'Tumis bumbu halus bersama serai dan daun salam hingga harum.'],
                    ['step' => 3, 'instruction' => 'Masukkan daging sapi, aduk hingga berubah warna.'],
                    ['step' => 4, 'instruction' => 'Tuang santan, masa dengan api sedang sambil terus diaduk.'],
                    ['step' => 5, 'instruction' => 'Kecilkan api, masak selama 3-4 jam hingga santan mengering dan rendang berwarna cokelat.'],
                ],
                'prep_time'     => 15,
                'cook_time'     => 180,
                'difficulty'    => 'hard',
                'calories'      => 450,
                'servings'      => 6,
                'allergens'     => [],
                'is_vip_content'=> false,
                'video_url'     => 'https://www.youtube.com/watch?v=DMcFqtm1lfY',
                'image'         => 'recipes/rendang_daging.png',
                'status'        => 'published',
                'tags'          => ['Tradisional', 'Gurih', 'Pedas'],
            ],
            [
                'chef_id'       => $chefRina->id,
                'category_id'   => $catIndo->id,
                'title'         => 'Nasi Goreng Kampung Spesial',
                'description'   => 'Nasi goreng dengan bumbu kampung sederhana namun penuh cita rasa. Cocok untuk sarapan pagi yang cepat dan lezat.',
                'ingredients'   => [
                    ['name' => 'Nasi putih', 'amount' => '3', 'unit' => 'piring'],
                    ['name' => 'Telur ayam', 'amount' => '2', 'unit' => 'butir'],
                    ['name' => 'Bawang merah', 'amount' => '5', 'unit' => 'siung'],
                    ['name' => 'Bawang putih', 'amount' => '3', 'unit' => 'siung'],
                    ['name' => 'Cabai rawit', 'amount' => '5', 'unit' => 'buah'],
                    ['name' => 'Kecap manis', 'amount' => '2', 'unit' => 'sdm'],
                    ['name' => 'Garam & merica', 'amount' => 'secukupnya', 'unit' => ''],
                    ['name' => 'Minyak goreng', 'amount' => '3', 'unit' => 'sdm'],
                ],
                'cooking_steps' => [
                    ['step' => 1, 'instruction' => 'Haluskan bawang merah, bawang putih, dan cabai rawit.'],
                    ['step' => 2, 'instruction' => 'Panaskan minyak, tumis bumbu halus hingga harum dan matang.'],
                    ['step' => 3, 'instruction' => 'Masukkan telur, orak-arik hingga setengah matang.'],
                    ['step' => 4, 'instruction' => 'Masukkan nasi, aduk rata dengan bumbu.'],
                    ['step' => 5, 'instruction' => 'Tambahkan kecap manis, garam, dan merica. Aduk rata.'],
                    ['step' => 6, 'instruction' => 'Sajikan dengan kerupuk, acar, dan irisan timun.'],
                ],
                'prep_time'     => 10,
                'cook_time'     => 15,
                'difficulty'    => 'easy',
                'calories'      => 380,
                'servings'      => 2,
                'allergens'     => ['eggs'],
                'is_vip_content'=> false,
                'video_url'     => 'https://www.youtube.com/watch?v=W1zb_ugYlu8',
                'image'         => 'recipes/nasi_goreng.png',
                'status'        => 'published',
                'tags'          => ['Cepat', 'Anti-Gagal', 'Untuk Pemula', 'Budget Friendly'],
            ],
            [
                'chef_id'       => $chefRina->id,
                'category_id'   => $catIndo->id,
                'title'         => 'Sate Ayam Madura',
                'description'   => 'Sate ayam khas Madura yang disajikan dengan saus kacang legit, kecap manis, irisan bawang merah, dan cabai rawit segar.',
                'ingredients'   => [
                    ['name' => 'Fillet paha ayam', 'amount' => '500', 'unit' => 'gram'],
                    ['name' => 'Kacang tanah goreng', 'amount' => '150', 'unit' => 'gram'],
                    ['name' => 'Bawang merah', 'amount' => '8', 'unit' => 'siung'],
                    ['name' => 'Bawang putih', 'amount' => '4', 'unit' => 'siung'],
                    ['name' => 'Kecap manis', 'amount' => '5', 'unit' => 'sdm'],
                    ['name' => 'Garam & gula merah', 'amount' => 'secukupnya', 'unit' => ''],
                    ['name' => 'Tusuk sate', 'amount' => 'secukupnya', 'unit' => ''],
                ],
                'cooking_steps' => [
                    ['step' => 1, 'instruction' => 'Potong daging ayam dadu, tusukkan ke tusuk sate.'],
                    ['step' => 2, 'instruction' => 'Haluskan kacang tanah, bawang merah, bawang putih, dan gula merah. Masak dengan sedikit air hingga berminyak.'],
                    ['step' => 3, 'instruction' => 'Ambil 2 sdm saus kacang, campur dengan kecap manis dan minyak untuk bumbu olesan.'],
                    ['step' => 4, 'instruction' => 'Bakar sate di atas bara atau panggangan sambil diolesi bumbu oles hingga matang kecokelatan.'],
                    ['step' => 5, 'instruction' => 'Sajikan sate ayam dengan siraman saus kacang sisa, kecap manis, dan irisan bawang merah.'],
                ],
                'prep_time'     => 2,
                'cook_time'     => 8,
                'difficulty'    => 'medium',
                'calories'      => 410,
                'servings'      => 4,
                'allergens'     => ['peanuts'],
                'is_vip_content'=> false,
                'video_url'     => 'https://www.youtube.com/watch?v=bbqkH_o8hDU',
                'image'         => 'recipes/sate_ayam.png',
                'status'        => 'published',
                'tags'          => ['Tradisional', 'Gurih', 'Bakar'],
            ],
            [
                'chef_id'       => $chefRina->id,
                'category_id'   => $catIndo->id,
                'title'         => 'Soto Ayam Lamongan',
                'description'   => 'Soto ayam dengan kuah kuning gurih khas Lamongan yang segar, dilengkapi dengan bubuk koya gurih terbuat dari kerupuk udang.',
                'ingredients'   => [
                    ['name' => 'Daging ayam', 'amount' => '1/2', 'unit' => 'ekor'],
                    ['name' => 'Bawang putih', 'amount' => '6', 'unit' => 'siung'],
                    ['name' => 'Bawang merah', 'amount' => '8', 'unit' => 'siung'],
                    ['name' => 'Kemiri sangrai', 'amount' => '4', 'unit' => 'butir'],
                    ['name' => 'Kunyit bakar', 'amount' => '3', 'unit' => 'cm'],
                    ['name' => 'Kerupuk udang & bawang putih goreng (untuk koya)', 'amount' => 'secukupnya', 'unit' => ''],
                    ['name' => 'Soun & kol iris', 'amount' => 'secukupnya', 'unit' => ''],
                ],
                'cooking_steps' => [
                    ['step' => 1, 'instruction' => 'Rebus ayam untuk membuat kaldu soto.'],
                    ['step' => 2, 'instruction' => 'Haluskan bawang putih, bawang merah, kemiri, dan kunyit. Tumis hingga harum.'],
                    ['step' => 3, 'instruction' => 'Masukkan tumisan bumbu ke dalam air rebusan ayam. Bumbui garam, merica, dan gula.'],
                    ['step' => 4, 'instruction' => 'Angkat ayam, suwir-suwir dagingnya.'],
                    ['step' => 5, 'instruction' => 'Buat koya: Haluskan kerupuk udang matang bersama bawang putih goreng sampai menjadi bubuk.'],
                    ['step' => 6, 'instruction' => 'Tata kol, soun, ayam suwir di mangkuk. Tuangkan kuah soto panas dan taburi bubuk koya.'],
                ],
                'prep_time'     => 2,
                'cook_time'     => 7,
                'difficulty'    => 'medium',
                'calories'      => 320,
                'servings'      => 4,
                'allergens'     => ['seafood'],
                'is_vip_content'=> false,
                'video_url'     => 'https://www.youtube.com/watch?v=cqSDDmYqRgg',
                'image'         => 'recipes/soto_ayam.png',
                'status'        => 'published',
                'tags'          => ['Tradisional', 'Kuah', 'Segar'],
            ],

            // ── CHEF BUDI SANTOSO (Asian & Fusion) ─────────────────────────────────
            [
                'chef_id'       => $chefBudi->id,
                'category_id'   => $catAsia->id,
                'title'         => 'Ramen Tonkotsu Homemade',
                'description'   => 'Ramen kuah tonkotsu dengan kaldu tulang babi yang dimasak selama 12 jam hingga creamy dan kaya umami. Versi premium dengan video tutorial eksklusif.',
                'ingredients'   => [
                    ['name' => 'Mie ramen segar', 'amount' => '400', 'unit' => 'gram'],
                    ['name' => 'Tulang babi', 'amount' => '1', 'unit' => 'kg'],
                    ['name' => 'Telur rebus', 'amount' => '4', 'unit' => 'butir'],
                    ['name' => 'Chashu (daging babi gulung)', 'amount' => '200', 'unit' => 'gram'],
                    ['name' => 'Nori (rumput laut)', 'amount' => '4', 'unit' => 'lembar'],
                    ['name' => 'Bawang daun', 'amount' => '2', 'unit' => 'batang'],
                    ['name' => 'Tare (saus dasar)', 'amount' => '4', 'unit' => 'sdm'],
                ],
                'cooking_steps' => [
                    ['step' => 1, 'instruction' => 'Rebus tulang babi selama 12 jam dengan api kecil hingga kaldu menjadi putih dan creamy.'],
                    ['step' => 2, 'instruction' => 'Buat tare dari kecap, mirin, dan sake.'],
                    ['step' => 3, 'instruction' => 'Rebus mie sesuai petunjuk, tiriskan.'],
                    ['step' => 4, 'instruction' => 'Siapkan mangkuk, tuang tare dan kaldu tonkotsu panas.'],
                    ['step' => 5, 'instruction' => 'Tata mie, telur, chashu, nori, dan bawang daun di atasnya.'],
                ],
                'prep_time'     => 30,
                'cook_time'     => 720,
                'difficulty'    => 'hard',
                'calories'      => 650,
                'servings'      => 4,
                'allergens'     => ['gluten', 'eggs'],
                'is_vip_content'=> true,
                'video_url'     => 'https://www.youtube.com/watch?v=uPqzY8rZLZM',
                'image'         => 'recipes/ramen_tonkotsu.png',
                'status'        => 'published',
                'tags'          => ['Restoran Style', 'Gurih'],
            ],
            [
                'chef_id'       => $chefBudi->id,
                'category_id'   => $catSeafood->id,
                'title'         => 'Udang Saus Padang Pedas',
                'description'   => 'Udang segar dimasak dengan saus padang yang pedas dan gurih. Sajian seafood premium yang mudah dibuat di rumah.',
                'ingredients'   => [
                    ['name' => 'Udang tiger', 'amount' => '500', 'unit' => 'gram'],
                    ['name' => 'Cabai merah', 'amount' => '8', 'unit' => 'buah'],
                    ['name' => 'Tomat merah', 'amount' => '2', 'unit' => 'buah'],
                    ['name' => 'Bawang bombay', 'amount' => '1', 'unit' => 'buah'],
                    ['name' => 'Saus tomat', 'amount' => '3', 'unit' => 'sdm'],
                    ['name' => 'Saus tiram', 'amount' => '2', 'unit' => 'sdm'],
                ],
                'cooking_steps' => [
                    ['step' => 1, 'instruction' => 'Bersihkan udang, belah punggung, marinasi dengan garam dan merica.'],
                    ['step' => 2, 'instruction' => 'Tumis bawang bombay hingga harum, masukkan cabai yang sudah dihaluskan.'],
                    ['step' => 3, 'instruction' => 'Masukkan tomat, saus tomat, dan saus tiram. Aduk rata.'],
                    ['step' => 4, 'instruction' => 'Masukkan udang, masak hingga matang dan saus mengental.'],
                    ['step' => 5, 'instruction' => 'Sajikan dengan nasi putih hangat.'],
                ],
                'prep_time'     => 15,
                'cook_time'     => 20,
                'difficulty'    => 'medium',
                'calories'      => 280,
                'servings'      => 3,
                'allergens'     => ['seafood'],
                'is_vip_content'=> false,
                'video_url'     => 'https://www.youtube.com/watch?v=jYAo-UmbLGk&t=262s',
                'image'         => 'recipes/udang_padang.png',
                'status'        => 'published',
                'tags'          => ['Pedas', 'Gurih'],
            ],
            [
                'chef_id'       => $chefBudi->id,
                'category_id'   => $catAsia->id,
                'title'         => 'Tom Yum Goong',
                'description'   => 'Sup khas Thailand yang memiliki kombinasi rasa asam, pedas, dan gurih yang menyegarkan dengan udang segar dan jamur.',
                'ingredients'   => [
                    ['name' => 'Udang kupas', 'amount' => '300', 'unit' => 'gram'],
                    ['name' => 'Jamur kancing', 'amount' => '100', 'unit' => 'gram'],
                    ['name' => 'Serai memarkan', 'amount' => '2', 'unit' => 'batang'],
                    ['name' => 'Lengkuas iris', 'amount' => '3', 'unit' => 'cm'],
                    ['name' => 'Daun jeruk purut', 'amount' => '5', 'unit' => 'lembar'],
                    ['name' => 'Perasan jeruk nipis', 'amount' => '3', 'unit' => 'sdm'],
                    ['name' => 'Nam Prik Pao (pasta cabai)', 'amount' => '2', 'unit' => 'sdm'],
                ],
                'cooking_steps' => [
                    ['step' => 1, 'instruction' => 'Rebus kaldu udang, masukkan serai, lengkuas, dan daun jeruk.'],
                    ['step' => 2, 'instruction' => 'Tambahkan pasta cabai Thailand dan kecap ikan. Aduk rata.'],
                    ['step' => 3, 'instruction' => 'Masukkan jamur dan udang, masak hingga udang berubah warna.'],
                    ['step' => 4, 'instruction' => 'Matikan api, masukkan perasan jeruk nipis dan daun ketumbar sebelum disajikan.'],
                ],
                'prep_time'     => 3,
                'cook_time'     => 10,
                'difficulty'    => 'medium',
                'calories'      => 240,
                'servings'      => 3,
                'allergens'     => ['seafood'],
                'is_vip_content'=> true,
                'video_url'     => 'https://www.youtube.com/watch?v=YW1ABCvBDt8',
                'image'         => 'recipes/tom_yum.png',
                'status'        => 'published',
                'tags'          => ['Sup', 'Asam Pedas', 'Thailand'],
            ],
            [
                'chef_id'       => $chefBudi->id,
                'category_id'   => $catAsia->id,
                'title'         => 'Beef Teriyaki Klasik',
                'description'   => 'Daging sapi iris tipis (shortplate) ditumis dengan saus teriyaki gurih manis khas Jepang, disajikan dengan taburan wijen.',
                'ingredients'   => [
                    ['name' => 'Daging sapi slice', 'amount' => '350', 'unit' => 'gram'],
                    ['name' => 'Bawang bombay iris', 'amount' => '1/2', 'unit' => 'buah'],
                    ['name' => 'Kecap asin Jepang (shoyu)', 'amount' => '3', 'unit' => 'sdm'],
                    ['name' => 'Mirin / Madu', 'amount' => '2', 'unit' => 'sdm'],
                    ['name' => 'Jahe parut', 'amount' => '1', 'unit' => 'sdt'],
                    ['name' => 'Bawang putih cincang', 'amount' => '3', 'unit' => 'siung'],
                ],
                'cooking_steps' => [
                    ['step' => 1, 'instruction' => 'Campurkan shoyu, mirin/madu, jahe parut, dan bawang putih untuk bumbu saus.'],
                    ['step' => 2, 'instruction' => 'Marinasi daging sapi dengan setengah bagian saus selama 15 menit.'],
                    ['step' => 3, 'instruction' => 'Tumis bawang bombay hingga layu, masukkan daging sapi beserta bumbu marinasinya.'],
                    ['step' => 4, 'instruction' => 'Tuang sisa saus teriyaki, masak dengan api besar hingga daging matang dan saus meresap.'],
                    ['step' => 5, 'instruction' => 'Taburi biji wijen sangrai dan daun bawang.'],
                ],
                'prep_time'     => 2,
                'cook_time'     => 6,
                'difficulty'    => 'easy',
                'calories'      => 480,
                'servings'      => 2,
                'allergens'     => ['gluten'],
                'is_vip_content'=> false,
                'video_url'     => 'https://www.youtube.com/watch?v=e7b2URagcrA',
                'image'         => 'recipes/beef_teriyaki.png',
                'status'        => 'published',
                'tags'          => ['Cepat', 'Manis Gurih', 'Jepang'],
            ],

            // ── CHEF DEWI KUSUMA (Dessert & Pastry) ────────────────────────────────
            [
                'chef_id'       => $chefDewi->id,
                'category_id'   => $catDessert->id,
                'title'         => 'Lapis Legit Premium Saffron',
                'description'   => 'Lapis legit dengan sentuhan saffron yang mewah. Resep rahasia dengan teknik memanggang berlapis yang membutuhkan kesabaran dan ketelitian tinggi. Tersedia video tutorial eksklusif.',
                'ingredients'   => [
                    ['name' => 'Tepung terigu', 'amount' => '100', 'unit' => 'gram'],
                    ['name' => 'Margarin', 'amount' => '500', 'unit' => 'gram'],
                    ['name' => 'Telur kuning', 'amount' => '30', 'unit' => 'butir'],
                    ['name' => 'Gula pasir halus', 'amount' => '200', 'unit' => 'gram'],
                    ['name' => 'Saffron', 'amount' => '1', 'unit' => 'gram'],
                    ['name' => 'Susu kental manis', 'amount' => '2', 'unit' => 'sdm'],
                    ['name' => 'Bumbu spekuk', 'amount' => '1', 'unit' => 'sdt'],
                ],
                'cooking_steps' => [
                    ['step' => 1, 'instruction' => 'Kocok margarin hingga putih dan fluffy, sisihkan.'],
                    ['step' => 2, 'instruction' => 'Kocok telur dan gula hingga mengembang dan berwarna pucat.'],
                    ['step' => 3, 'instruction' => 'Campurkan kedua adonan, masukkan tepung secara bertahap.'],
                    ['step' => 4, 'instruction' => 'Bagi adonan menjadi 2: satu polos, satu dengan saffron.'],
                    ['step' => 5, 'instruction' => 'Panggang berlapis satu per satu dalam oven 180°C dengan posisi api atas.'],
                    ['step' => 6, 'instruction' => 'Ulangi proses hingga 18-20 lapisan. Panggang lapisan terakhir sampai matang.'],
                ],
                'prep_time'     => 45,
                'cook_time'     => 120,
                'difficulty'    => 'hard',
                'calories'      => 520,
                'servings'      => 20,
                'allergens'     => ['gluten', 'eggs', 'dairy'],
                'is_vip_content'=> true,
                'video_url'     => 'https://www.youtube.com/watch?v=A7XveUfM6Gk',
                'image'         => 'recipes/lapis_legit.png',
                'status'        => 'published',
                'tags'          => ['Tradisional', 'Restoran Style'],
            ],
            [
                'chef_id'       => $chefDewi->id,
                'category_id'   => $catSehat->id,
                'title'         => 'Smoothie Bowl Tropical',
                'description'   => 'Sarapan sehat berbasis buah tropis dengan topping granola dan biji chia. Rendah kalori, tinggi serat dan vitamin.',
                'ingredients'   => [
                    ['name' => 'Pisang beku', 'amount' => '2', 'unit' => 'buah'],
                    ['name' => 'Mangga beku', 'amount' => '100', 'unit' => 'gram'],
                    ['name' => 'Yogurt plain', 'amount' => '100', 'unit' => 'ml'],
                    ['name' => 'Granola', 'amount' => '50', 'unit' => 'gram'],
                    ['name' => 'Biji chia', 'amount' => '1', 'unit' => 'sdm'],
                    ['name' => 'Buah naga', 'amount' => '50', 'unit' => 'gram'],
                    ['name' => 'Madu', 'amount' => '1', 'unit' => 'sdt'],
                ],
                'cooking_steps' => [
                    ['step' => 1, 'instruction' => 'Blender pisang beku, mangga, dan yogurt hingga smooth dan creamy.'],
                    ['step' => 2, 'instruction' => 'Tuang ke mangkuk, ratakan permukaannya.'],
                    ['step' => 3, 'instruction' => 'Tata granola, buah naga, dan topping lain di atasnya.'],
                    ['step' => 4, 'instruction' => 'Taburkan biji chia dan drizzle madu. Sajikan segera.'],
                ],
                'prep_time'     => 10,
                'cook_time'     => 5,
                'difficulty'    => 'easy',
                'calories'      => 180,
                'servings'      => 1,
                'allergens'     => ['dairy'],
                'is_vip_content'=> false,
                'video_url'     => 'https://www.youtube.com/watch?v=fXLYqqxB2wc&t=45s',
                'image'         => 'recipes/smoothie_bowl.png',
                'status'        => 'published',
                'tags'          => ['Makanan Sehat', 'Rendah Kalori', 'Untuk Pemula', 'Cepat'],
            ],
            [
                'chef_id'       => $chefDewi->id,
                'category_id'   => $catDessert->id,
                'title'         => 'Apple Pie Klasik',
                'description'   => 'Pai apel klasik khas Amerika dengan crust renyah bermentega tinggi dan isian apel kayu manis yang manis hangat menggugah selera.',
                'ingredients'   => [
                    ['name' => 'Tepung terigu protein sedang', 'amount' => '300', 'unit' => 'gram'],
                    ['name' => 'Mentega dingin', 'amount' => '150', 'unit' => 'gram'],
                    ['name' => 'Air es', 'amount' => '5', 'unit' => 'sdm'],
                    ['name' => 'Apel Granny Smith iris', 'amount' => '4', 'unit' => 'buah'],
                    ['name' => 'Gula pasir & bubuk kayu manis', 'amount' => 'secukupnya', 'unit' => ''],
                    ['name' => 'Lemon juice', 'amount' => '1', 'unit' => 'sdm'],
                ],
                'cooking_steps' => [
                    ['step' => 1, 'instruction' => 'Campur tepung dan mentega dingin hingga berbutir kasar. Tambahkan air es sedikit demi sedikit, bulatkan adonan crust, dinginkan di kulkas 30 menit.'],
                    ['step' => 2, 'instruction' => 'Campur apel iris dengan gula, kayu manis, dan air lemon.'],
                    ['step' => 3, 'instruction' => 'Gilas adonan crust, letakkan di loyang pai. Masukkan isian apel.'],
                    ['step' => 4, 'instruction' => 'Tutup atasnya dengan adonan crust bermotif kepang/lattice. Olesi kuning telur.'],
                    ['step' => 5, 'instruction' => 'Panggang suhu 190°C selama 45-50 menit hingga kecokelatan.'],
                ],
                'prep_time'     => 3,
                'cook_time'     => 10,
                'difficulty'    => 'medium',
                'calories'      => 340,
                'servings'      => 8,
                'allergens'     => ['gluten', 'dairy'],
                'is_vip_content'=> false,
                'video_url'     => 'https://www.youtube.com/watch?v=E4XcJa6ovAU',
                'image'         => 'recipes/apple_pie.png',
                'status'        => 'published',
                'tags'          => ['Pai', 'Kue', 'Manis'],
            ],
            [
                'chef_id'       => $chefDewi->id,
                'category_id'   => $catDessert->id,
                'title'         => 'Chocolate Lava Cake',
                'description'   => 'Kue cokelat panggang dengan bagian tengah cair meleleh (lava) cokelat Belgia murni yang disajikan hangat dengan es krim vanila.',
                'ingredients'   => [
                    ['name' => 'Dark chocolate premium', 'amount' => '100', 'unit' => 'gram'],
                    ['name' => 'Mentega', 'amount' => '50', 'unit' => 'gram'],
                    ['name' => 'Telur utuh', 'amount' => '2', 'unit' => 'butir'],
                    ['name' => 'Kuning telur', 'amount' => '2', 'unit' => 'butir'],
                    ['name' => 'Gula pasir', 'amount' => '3', 'unit' => 'sdm'],
                    ['name' => 'Tepung terigu', 'amount' => '3', 'unit' => 'sdm'],
                ],
                'cooking_steps' => [
                    ['step' => 1, 'instruction' => 'Tim dark chocolate bersama mentega hingga meleleh rata.'],
                    ['step' => 2, 'instruction' => 'Kocok telur, kuning telur, dan gula pasir hingga mengembang kental.'],
                    ['step' => 3, 'instruction' => 'Masukkan lelehan cokelat ke kocokan telur. Ayak tepung terigu, aduk lipat perlahan.'],
                    ['step' => 4, 'instruction' => 'Tuang adonan ke ramekin yang sudah dioles mentega dan ditabur cokelat bubuk.'],
                    ['step' => 5, 'instruction' => 'Panggang di oven 200°C selama tepat 10-12 menit hingga bagian pinggir kokoh namun tengah masih lembut.'],
                    ['step' => 6, 'instruction' => 'Balik ke piring saji, taburi gula halus, sajikan dengan es krim vanila.'],
                ],
                'prep_time'     => 1,
                'cook_time'     => 3,
                'difficulty'    => 'medium',
                'calories'      => 420,
                'servings'      => 2,
                'allergens'     => ['eggs', 'gluten', 'dairy'],
                'is_vip_content'=> true,
                'video_url'     => 'https://www.youtube.com/watch?v=0gS6qZYxik0',
                'image'         => 'recipes/lava_cake.png',
                'status'        => 'published',
                'tags'          => ['Manis', 'Leleh', 'Cokelat'],
            ],
        ];

        foreach ($recipes as $data) {
            $tags = $data['tags'] ?? [];
            unset($data['tags']);

            $recipe = Recipe::updateOrCreate(['title' => $data['title']], $data);

            // Attach tags
            $tagIds = Tag::whereIn('name', $tags)->pluck('id');
            $recipe->tags()->sync($tagIds);
        }
    }
}
